import {
  Api,
  Close,
  Curtains,
  Event,
  Factory,
  GridView,
  Info,
  LinkedIn,
  Phone,
  Pinterest,
  Pix,
  Tornado,
  Twitter,
  Warehouse,
  YouTube,Menu,
  Home,
  CardGiftcard,
  Pages,
  Diversity2,
  Stroller,
  Login,
  Business,
  EmojiObjects,
  RateReview
} from "@mui/icons-material";


export default {
  Api: <Api />,
  Business:<Business/>,
  Close: <Close />,
  Curtains: <Curtains />,
  Diversity2:<Diversity2/>,
  Event: <Event />,
  Factory: <Factory />,
  GridView: <GridView />,
  CardGiftcard: <CardGiftcard />,
  Home:<Home/>,
  Info: <Info />,
  EmojiObjects:<EmojiObjects/>,
  LinkedIn: <LinkedIn />,
  Login:<Login/>,
  Menu: <Menu />,
  Phone: <Phone />,
  Pages:<Pages/>,
  Pinterest: <Pinterest />,
  Pix: <Pix />,
  RateReview:<RateReview/>,
  Stroller:<Stroller/>,
  Tornado: <Tornado />,
  Twitter: <Twitter />,
  Warehouse: <Warehouse />,
  YouTube: <YouTube />,
};
