export const BaseImageURL = {
  "PRODUCT-FAMILY": "https://sivaiot.co/img/product-family/",
};

export const Route_Path = {
  HOME: "/",
  RFID_INDUSTRIES: "/rfid-industries",
  RFID_INDUSTRIES_URL: "/industries/:URL",
  PRODUCTS: "/rfid-tags-and-labels",
  PRODUCTS_DETAILS: "/rfid-tags-and-labels-details",
  PRODUCT_FAMILY: "/rfid-product-families",
  PRODUCT_FAMILY_DETAILS: "/rfid-product-families-details",
  // PRODUCT_FAMILY_URL: "/rfid-product-families/:URL",
  Application: "/applications",
  Applications_details: "/applications-details",
  ABOUT: "/about-siva-iot",
  CAREERS: "/careers",
  LEADERSHIP: "/leadership",
  RFID_CONTACT: "/rfid-contact",
  DESIGN_LAB: "/design-lab",
  CSR_POLICY: "/csr-policy",
  FAQ: "/faq",
  BLOG: "/blog",
  BLOG_URL: "/blog/:URL",
  BECOME_CHANNEL_PARTNER: "/become-channel-partner",
  STANDER_TERMS_AND_CONDITIONS: "/standard-terms-and-conditions",
  TERMS_OF_USE: "/terms-of-use",
  PRIVACY_POLICY: "/privacy-policy",
  DATASHEET_NAME: "/datasheet/:name",
  DATASHEET: "/datasheet",
  WB: "/wb",
  RFID_ACCESS_CONTROL: "/rfid-access-control",
  THERMAL_RFID_EVENT_TICKETING: "/thermal-rfid-event-ticketing",
  WB_WRISTBANDS: "/wb/wristbands",
  WB_CARD_KEYS_FOBS: "/wb/card-keys-fobs",
  WB_ULTIMOID_DIRECTTHERMAL: "/wb/ultimoiddirectthermal",
  WB_ULTIMOID_ECODURA: "/wb/ultimoidecodura",
  WB_ULTIMOID_SILICON: "/wb/silicone-wristbands",
  WB_ULTIMOID_POLY: "/wb/laminated-wristbands",
  WB_ULTIMOID_FABRIC: "/wb/fabric-wristbands",
  WB_ULTIMOID_TYVEK: "/wb/ultimoidtyvek",
  WB_POLY_IN_SHEETS: "/wb/poly-in-sheets",
  PARTNERS: "/partners",
  PARTNERS_PRODUCT_FAMILY: "/partners/rfid-product-families",
  PARTNERS_PRODUCTS: "/partners/rfid-tags-and-labels",
  PORTAL: "/portal",
  PARTNER_LOGIN: "/partner",
  PROFILE: "/profile",
  PARTNERS_PRICE_LIST: "/partners/price-list",
  PARTNERS_NDA: "/partners/nda",
  PARTNERS_RFID_CONTACT: "/partners/rfid-contact",
  BLOCK: "/block",
  WRONG_PATH: "*",
};

export const IPList = ["27.107.144.250", "103.245.70.171"];
export const restrictedCountries = ["CN"];
